USE Trains
GO

GO
CREATE TABLE TrainTypes
( TTID INT PRIMARY KEY,
  TTName VARCHAR(50),
  TTDescription VARCHAR(100)
 )

CREATE TABLE Trains
( TID INT PRIMARY KEY,
  TName VARCHAR(50),
  TTID INT REFERENCES TrainTypes(TTID)
)

CREATE TABLE Station
( SID INT PRIMARY KEY,
  SName VARCHAR (50) UNIQUE
)

CREATE TABLE Routes
( RID INT PRIMARY KEY,
  RName VARCHAR(50) UNIQUE,
  TID INT REFERENCES Trains(TID)
)

CREATE TABLE StationRoutes
( SID INT REFERENCES Station(SID),
  RID INT REFERENCES Routes(RID),
  Arrival TIME,
  Departure TIME,
  PRIMARY KEY (SID,RID)
)